### ISSUE TITLE
VSIX - error updating to version 1.8.24

### ISSUE THREAD

**Issue by jackBzzz** [ligershark/Farticus#2]
### Installed product versions
- Visual Studio: 2017 Enterprise
- This extension: 1.8.23

### Description
Replace this text with a short description

### Steps to recreate
1. Have VS with extension version 1.8.23 installed
2. go to Tools - Extensions and updates
3. choose update for this extension
4. close VS
5. VSIX installer starts
(extension does not have a digital signature btw)
6. Choose "Modify"
7.Message received: "Modifications failed"

Select install log lines:
10/2/2018 17:36:28 - Upgrading 'Farticus', version 1.8.23 to version 1.8.24.
10/2/2018 17:36:30 - Version value mismatch. VsixManifest value: '1.8.24'; Catalog manifest value: '1.8.23'; Package manifest value: '1.8.24'
10/2/2018 17:36:30 - Install Error : System.InvalidOperationException: The value of property 'Version' is not consistent amongst all manifests.

### Current behavior
Version values mismatch.

### Expected behavior
Version values should be all the same.

**Comment by madskristensen** [comment]
Fixed. Try again
